language: go
sudo: enabled
go:
  - "1.10.3"
addons:
  apt:
    packages:
      - curl
notifications:
  email: false
services:
  - docker
before_install:
  - go get github.com/mattn/goveralls
script:
  - $GOPATH/bin/goveralls -service=travis-ci