# logging section
logging:

common:
  # crypto section
  crypto:
    # hash
    hash: SHA256
    # sign
    sign: ECDSA

  # database section
  database:
    type: badger

    badger:
      dir: /var/topa/data